todo_manager/todo_list/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import index_view, ToDoListIndex, ToDoListView, ToDoListDoneView, ToDoDetailView

app_name = 'todo_list'

urlpatterns = [
    path('', ToDoListView.as_view(), name='index'),
    # path('', ToDoListIndex.as_view(), name='index')
    # path('', index_view, name='index'),
    path('done/', ToDoListDoneView.as_view(), name='done'),
    path('<int:pk>/detail/', ToDoDetailView.as_view(), name='detail')
]

todo_manager/todo_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html"), name='home'),
    path('todos/', include("todo_list.urls", namespace='todo_list'))
]

todo_manager/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
</head>
<body>
    {% include 'components/navbar.html' %}

    {% block body %}
        Base body
    {% endblock %}

    <footer>
        &copy; Django TODO App
        {% block footer %}

        {% endblock %}
    </footer>
</body>
</html>

todo_manager/templates/components/navbar.html
<nav>
    <ul>
       <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'todo_list:index' %}">About</a></li>
    </ul>
</nav>

todo_manager/templates/index.html
{% extends 'base.html' %}

{% block title %}
    TODO App Index
{% endblock %}

{% block body %}
    <h1>Welcome to our TODO App!</h1>
    <h2>Work in progress</h2>
    <h3>It is {% now 'jS F Y' %}</h3>
{% endblock %}

todo_manager/todo_list/templates/todo_list/base.html
{% extends 'base.html' %}

{% block footer %}
    Todo list
{% endblock %}
10мин

todo_manager/todo_list/templates/todo_list/components/todoitem_list.html
   <ul>
        {% for todo_item in todo_items %}
            <li>
                <a href="{% url 'todo_list:detail' pk=todo_item.pk %}">
                    {{ todo_item.title }}
                    {% if todo_item.done %}
                        😉
                    {% else %}
                        😤
                    {% endif %}
                </a>
            </li>
        {% endfor %}
    </ul>

todo_manager/todo_list/templates/todo_list/index.html
{% extends 'todo_list/base.html' %}

{% block title %}
    ToDo List App
{% endblock %}

{% block body %}
    <a href="{% url 'todo_list:done' %}">Done</a>

    <h1>ToDo List App</h1>
    <h2>ToDos:</h2>
    {% include 'todo_list/components/todoitem_list.html' %}
{% endblock %}

todo_manager/todo_list/templates/todo_list/todoitem_detail.html
{% extends 'todo_list/base.html' %}

{% block title %}
  ToDo {{ object.pk }}
{% endblock %}

{% block body %}
  <h3>ToDos:</h3>
  <div>
    <div>Title:<strong>{{ object.title }}</strong>
    <div>Done:<strong>{{ object.done }}</strong></div>

    </div>
  </div>
{% endblock %}